from .prepare import (
    HOSTNAME,
    TG_API_TOKEN,
    OPENAI_API_KEY,
    BOT_NAME,
    DEBOUNCE_SECS,
    ENVIRONMENT,
    OPENAI_MODEL,
    DATABASE_URL,
    VK_API_SECRET,
    VK_API_CONFIRMATION_RESPONSE,
    VK_API_VERSION,
    VK_ACCESS_TOKEN,
)
